# Generated by Django 3.0.4 on 2020-08-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=30)),
                ('rmail', models.EmailField(max_length=254)),
                ('rpass', models.CharField(max_length=10)),
                ('rrpass', models.CharField(max_length=10)),
            ],
        ),
    ]
